---
name: Parse-BBCode
version: 0.07
author:
  - Tina Mueller
abstract: Module to turn BBCode into HTML or plain text
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::Accessor::Fast: 0.25
  Data::Dumper: 0
  URI::Escape: 0
  perl: 5.6.1
  strict: 0
  warnings: 0
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
provides:
  Parse::BBCode:
    file: lib/Parse/BBCode.pm
    version: 0.07
  Parse::BBCode::HTML:
    file: lib/Parse/BBCode/HTML.pm
    version: 0.02
  Parse::BBCode::Markdown:
    file: lib/Parse/BBCode/Markdown.pm
    version: 0.01
  Parse::BBCode::Tag:
    file: lib/Parse/BBCode/Tag.pm
    version: 0.02
  Parse::BBCode::XHTML:
    file: lib/Parse/BBCode/XHTML.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
